import path from 'node:path';
import { KINDS, LIMITS, PROVIDERS, RECALL_INVOCATION, ROLES } from '../shared/config.mjs';
import { decodeDataUrl } from '../shared/attachments.mjs';
import { asIso } from '../shared/ids.mjs';
import { oneLine, stripTags } from '../shared/text.mjs';
import { parseJsonlSource, pushAttachment, pushMessage, sessionState, touch } from './builder.mjs';
import { readJsonlAt } from './jsonl.mjs';
import { listDir, readJson } from './fsutil.mjs';
import { outputExcerpt, toolSummary } from './tools.mjs';

const PROVIDER = PROVIDERS.CLAUDE;

// Harness text injected into user turns. Removed before indexing.
const INJECTED_TAGS = ['system-reminder', 'local-command-caveat', 'local-command-stdout', 'local-command-stderr', 'command-message'];
const NOISE_PROMPTS = [/^\[Request interrupted by user[^\]]*\]$/, /^Caveat: The messages below were generated by the user/];
// Large attachment records (file snapshots, instructions, skill listings) never carry user words.
const SKIPPABLE_ATTACHMENT = /"attachment":\{"type":"(?!queued_command)/;

// "/name args" instead of the XML the harness stores for slash commands.
function slashCommand(text) {
  const name = text.match(/<command-name>([\s\S]*?)<\/command-name>/)?.[1]?.trim();
  if (!name) return text;
  const args = text.match(/<command-args>([\s\S]*?)<\/command-args>/)?.[1]?.trim() ?? '';
  const rest = text.replace(/<command-(name|args)>[\s\S]*?<\/command-\1>/g, '');
  return `${name.startsWith('/') ? name : `/${name}`}${args ? ` ${args}` : ''}${rest.trim() ? `\n${rest.trim()}` : ''}`;
}

export function cleanUserText(raw) {
  const text = stripTags(slashCommand(String(raw ?? '')), INJECTED_TAGS);
  return NOISE_PROMPTS.some(pattern => pattern.test(text)) ? '' : text;
}

function blockText(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content.filter(block => block?.type === 'text' && typeof block.text === 'string').map(block => block.text).join('\n');
}

function handleUser(state, record, position, out) {
  const ts = asIso(record.timestamp);
  const content = record.message?.content;
  if (record.isCompactSummary) {
    pushMessage(state, out, { role: ROLES.USER, kind: KINDS.SUMMARY, text: blockText(content), ts });
    return;
  }
  if (typeof content === 'string') {
    pushMessage(state, out, { role: ROLES.USER, text: cleanUserText(content), ts });
    return;
  }
  if (!Array.isArray(content)) return;
  const texts = [];
  const images = [];
  content.forEach((block, index) => {
    if (block?.type === 'text') texts.push(block.text);
    else if (block?.type === 'image' && block.source?.type === 'base64') images.push(index);
    else if (block?.type === 'tool_result') {
      const recall = state.recallCalls.indexOf(block.tool_use_id);
      if (recall !== -1) {
        state.recallCalls.splice(recall, 1);
        return;
      }
      const output = outputExcerpt(blockText(block.content));
      pushMessage(state, out, { role: ROLES.TOOL, kind: KINDS.OUTPUT, text: output, ts, meta: block.is_error ? { error: true } : undefined });
    }
  });
  const text = cleanUserText(texts.join('\n'));
  if (!text && images.length === 0) return;
  const seq = pushMessage(state, out, { role: ROLES.USER, text: text || '[image]', ts });
  images.forEach((blockIndex, ordinal) => {
    const source = content[blockIndex].source;
    pushAttachment(state, out, {
      seq,
      ordinal,
      dataUrl: `data:${String(source.media_type || 'application/octet-stream').toLowerCase()};base64,${source.data || ''}`,
      locator: { offset: position.offset, block: blockIndex },
    });
  });
}

function handleAssistant(state, record, out) {
  const ts = asIso(record.timestamp);
  const content = record.message?.content;
  if (record.message?.model && record.message.model !== '<synthetic>') state.model = record.message.model;
  if (typeof content === 'string') {
    pushMessage(state, out, { role: ROLES.ASSISTANT, text: content, ts });
    return;
  }
  if (!Array.isArray(content)) return;
  for (const block of content) {
    if (block?.type === 'text') pushMessage(state, out, { role: ROLES.ASSISTANT, text: block.text, ts });
    else if (block?.type === 'tool_use') {
      const summary = toolSummary(block.name, block.input);
      const recall = RECALL_INVOCATION.test(summary);
      if (recall && block.id) state.recallCalls.push(block.id);
      pushMessage(state, out, { role: ROLES.ASSISTANT, kind: KINDS.TOOL, text: summary, ts, meta: recall ? { recall: true } : undefined });
    }
  }
}

const parser = {
  init(source) {
    const meta = source.meta ?? {};
    const stem = path.basename(source.path, '.jsonl');
    return sessionState({
      provider: PROVIDER,
      nativeId: meta.parentNativeId ? `${meta.parentNativeId}:${meta.agentId ?? stem}` : stem,
      parentNativeId: meta.parentNativeId ?? null,
      origin: meta.origin ?? null,
      agentTitle: meta.agentTitle ?? null,
      agentType: meta.agentType ?? null,
      titles: {},
      cwd: null,
      gitBranch: null,
      model: null,
    });
  },

  skip(head) {
    return SKIPPABLE_ATTACHMENT.test(head) || head.includes('"type":"file-history-snapshot"') || head.includes('"type":"progress"');
  },

  record(state, record, position, out) {
    if (typeof record.cwd === 'string' && record.cwd) state.cwd = record.cwd;
    if (typeof record.gitBranch === 'string' && record.gitBranch && record.gitBranch !== 'HEAD') state.gitBranch = record.gitBranch;
    if (!state.origin && typeof record.entrypoint === 'string') state.origin = record.entrypoint === 'claude-desktop' ? 'desktop' : record.entrypoint;
    switch (record.type) {
      case 'user':
        if (record.isMeta !== true) handleUser(state, record, position, out);
        return;
      case 'assistant':
        handleAssistant(state, record, out);
        return;
      case 'custom-title':
        if (record.customTitle) state.titles.custom = oneLine(record.customTitle, LIMITS.TITLE_MAX_CHARS);
        return;
      case 'agent-name':
        if (record.agentName) state.titles.agent = oneLine(record.agentName, LIMITS.TITLE_MAX_CHARS);
        return;
      case 'ai-title':
        if (record.aiTitle) state.titles.ai = oneLine(record.aiTitle, LIMITS.TITLE_MAX_CHARS);
        return;
      case 'summary':
        if (record.summary) state.titles.summary = oneLine(record.summary, LIMITS.TITLE_MAX_CHARS);
        return;
      case 'attachment':
        if (record.attachment?.type === 'queued_command' && typeof record.attachment.prompt === 'string') {
          pushMessage(state, out, { role: ROLES.USER, text: cleanUserText(record.attachment.prompt), ts: asIso(record.timestamp) });
        }
        return;
      default:
        touch(state, asIso(record.timestamp));
    }
  },

  finish(state) {
    const titles = state.titles;
    const [title, titleSource] = titles.custom ? [titles.custom, 'user']
      : state.agentTitle ? [state.agentTitle, 'generated']
        : titles.agent ? [titles.agent, 'generated']
          : titles.ai ? [titles.ai, 'generated']
            : titles.summary ? [titles.summary, 'generated']
              : [state.firstPrompt, 'prompt'];
    const resumeId = state.parentNativeId ?? state.nativeId;
    return [{
      nativeId: state.nativeId,
      parentNativeId: state.parentNativeId,
      kind: state.parentNativeId ? 'subagent' : 'main',
      title: title ?? null,
      titleSource: title ? titleSource : null,
      firstPrompt: state.firstPrompt,
      cwd: state.cwd,
      gitBranch: state.gitBranch,
      model: state.model,
      origin: state.origin ?? 'cli',
      createdAt: state.createdAt,
      updatedAt: state.updatedAt,
      archived: false,
      resume: { command: 'claude', args: ['--resume', resumeId], cwd: state.cwd },
      meta: state.agentType ? { agentType: state.agentType } : {},
    }];
  },
};

// Subagent transcripts sit below their parent session, sometimes nested (workflows/).
async function subagentSources(sessionDir, parentNativeId, origin) {
  const walk = async dir => {
    const entries = await listDir(dir);
    const nested = await Promise.all(entries.map(async entry => {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) return walk(full);
      if (!entry.isFile() || !/^agent-.+\.jsonl$/i.test(entry.name)) return [];
      return [{ provider: PROVIDER, path: full, kind: 'jsonl', meta: { origin, parentNativeId, agentId: path.basename(entry.name, '.jsonl') } }];
    }));
    return nested.flat();
  };
  return walk(path.join(sessionDir, 'subagents'));
}

async function projectSources(projectsRoot, origin) {
  const projects = (await listDir(projectsRoot)).filter(entry => entry.isDirectory());
  const perProject = await Promise.all(projects.map(async project => {
    const projectDir = path.join(projectsRoot, project.name);
    const entries = await listDir(projectDir);
    const nested = await Promise.all(entries.map(async entry => {
      const full = path.join(projectDir, entry.name);
      if (entry.isFile() && entry.name.endsWith('.jsonl')) return [{ provider: PROVIDER, path: full, kind: 'jsonl', meta: { origin } }];
      return entry.isDirectory() ? subagentSources(full, entry.name, origin) : [];
    }));
    return nested.flat();
  }));
  return perProject.flat();
}

// Desktop Code tab and Cowork both keep local_<id>.json next to their sessions.
async function desktopSessionFiles(root) {
  const files = [];
  for (const account of await listDir(root)) {
    if (!account.isDirectory()) continue;
    for (const org of await listDir(path.join(root, account.name))) {
      if (!org.isDirectory()) continue;
      const orgDir = path.join(root, account.name, org.name);
      for (const entry of await listDir(orgDir)) {
        if (entry.isFile() && /^local_.+\.json$/.test(entry.name)) files.push(path.join(orgDir, entry.name));
        else if (entry.isDirectory() && /^local_/.test(entry.name)) files.push({ dir: path.join(orgDir, entry.name) });
      }
    }
  }
  return files;
}

export const claudeProvider = {
  id: PROVIDER,

  async discover(roots) {
    const cowork = (await desktopSessionFiles(roots.claudeCowork)).filter(item => typeof item === 'object');
    const all = await Promise.all([
      projectSources(roots.claudeProjects, 'cli'),
      ...cowork.map(item => projectSources(path.join(item.dir, '.claude', 'projects'), 'cowork')),
    ]);
    return all.flat();
  },

  // Titles, archive flags and origins that live outside the transcripts.
  async labels(roots) {
    const labels = [];
    for (const [root, origin] of [[roots.claudeDesktopSessions, 'desktop'], [roots.claudeCowork, 'cowork']]) {
      const files = (await desktopSessionFiles(root)).filter(file => typeof file === 'string');
      for (const data of await Promise.all(files.map(readJson))) {
        if (!data?.cliSessionId) continue;
        const folder = Array.isArray(data.userSelectedFolders) ? data.userSelectedFolders[0] : null;
        labels.push({
          nativeId: String(data.cliSessionId),
          title: data.title ? oneLine(data.title, LIMITS.TITLE_MAX_CHARS) : null,
          titleSource: data.titleSource === 'user' ? 'user' : 'generated',
          archived: data.isArchived === true,
          origin,
          cwd: origin === 'cowork' ? folder ?? null : null,
        });
      }
    }
    return labels;
  },

  async parse(source, cursor) {
    // A subagent's description and type live beside it; read only when parsing from the start.
    if (source.meta?.parentNativeId && !cursor?.state) {
      const meta = await readJson(source.path.replace(/\.jsonl$/i, '.meta.json'));
      source = { ...source, meta: { ...source.meta, agentTitle: meta?.description ? oneLine(meta.description, LIMITS.TITLE_MAX_CHARS) : null, agentType: meta?.agentType ?? null } };
    }
    return parseJsonlSource(source, cursor, parser);
  },

  async readAttachment(source, locator) {
    const record = await readJsonlAt(source.path, locator.offset);
    const block = record?.message?.content?.[locator.block];
    if (block?.type !== 'image' || block.source?.type !== 'base64') return null;
    return decodeDataUrl(`data:${String(block.source.media_type || 'application/octet-stream').toLowerCase()};base64,${block.source.data || ''}`);
  },
};

export async function claudeRetentionDays(roots) {
  const settings = await readJson(roots.claudeSettings);
  const value = Number(settings?.cleanupPeriodDays);
  return Number.isFinite(value) && value > 0 ? value : null;
}
